name: Run unit and doc tests

on: 
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        required: true
        default: '3.11'
        type: string

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Install package dependencies
      run: pip install -r requirements.txt
      
    - name: Install utest dependencies
      run: pip install -r utest/requirements.txt
      
    - name: Install the package
      run: pip install . 
    
    - name: Run unit tests
      run: make test

  doc-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Install package dependencies
      run: pip install -r requirements.txt
      
    - name: Install docs dependencies
      run: pip install -r docs/requirements.txt

    - name: Install Plotly
      run: pip install plotly
      
    - name: Install the package
      run: pip install . 
      
    - name: Make examples
      run: make examples
      
    - name: Make pictures
      run: make bravais-pictures
      
    - name: Build documentation
      run: make html
      
    - name: Run doctests
      run: make doctest
